name: fleet_mgt_dbt
version: '1.0'
config-version: 2

# This profile name must match the one defined in your profiles.yml (or via the DBT_PROFILES_DIR environment variable)
profile: my_dbt_project

# Define where your model files are located
# Update: use model-paths (instead of deprecated source-paths)
model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

# Optional: set default materializations for your models
models:
  fleet_mgt_dbt:
    +materialized: view
