my_dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST') }}"
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      port: "{{ env_var('DB_PORT', '5432') | int }}"
      dbname: "dbt_target"   # Target destination database for models
      schema: public         # This can be adjusted as needed
